# Generated by Django 2.2 on 2020-05-18 17:55

from django.db import migrations
import multimenus.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0004_auto_20170530_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=multimenus.fields.URLField(blank=True, null=True),
        ),
    ]
