# Generated by Django 2.2 on 2020-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0005_auto_20200518_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
