# Generated by Django 2.2 on 2021-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0006_auto_20200518_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
